---
title: "Workflow for a complex LMM example"
author: "Reinhold Kliegl"
---

* [Github Repository](https://github.com/RePsychLing/MRK17_Exp1) `git clone https://github.com/RePsychLing/MRK17_Exp1.git`

### Setting up

* In VSCode open julia REPL (&#8679;&#8984;P) and type ";" to access the shell
    * shell> `cd /dir/where/repo/goes/`
    * shell> `git clone https://github.com/RePsychLing/MRK17_Exp1.git`
    * shell> `cd MRK17_Exp1`
* Open the `MRK17_Exp1` directory in VSCode
* Open the file `MRK17_Exp1_rk01.jmd`
* Shift-cmd-P to open the commands window and search for `Julia: Start REPL`
* Type `]` in the Terminal window in VSCode to get the `pkg` prompt
* pkg> `activate .`
* Add/update some packages (get the `pkg` prompt with `]`)
    - pkg> `add MixedModels#master`
    - pkg> `st`
* Use backspace to get back to the julia prompt

Illustrate execution from `jmd` file.

Illustrate execution from `ipynb` file

* julia> `using Weave`
* julia> `convert_doc("MRK17_Exp1_rk01.jmd", "MRK17_Exp1_rk01.ipynb")`
* julia> `using IJulia`
* julia> `IJulia.notebook(dir=".")`

### Notes

* Don't look at fixed effects before model selection
                           * Preface random effect specification with `zerocorr` to  (equivalent to ||)
                           
                           ## Power Simulation{#powersim}
                           
                           [*Lisa DeBruine*](https://debruine.github.io)
                           
                           * [GitHub Repository](https://github.com/RePsychLing/sim-tutorial) `git clone https://github.com/RePsychLing/sim-tutorial`
                           * [MixedModelsSim package](https://github.com/RePsychLing/MixedModelsSim.jl)
                           - pkg> `add https://github.com/RePsychLing/MixedModelsSim.jl`
                           
                           ## ManyBabies{#mb1}
                           
                           *Christina Bergmann*
                             
                             * [GitHub Repository](https://github.com/RePsychLing/mb1) `git clone https://github.com/RePsychLing/mb1.git`