---
title: "Introduction"
author: "Douglas Bates"
---

* [GitHub Repository](https://github.com/RePsychLing/LMMComplexity)
    - `git clone https://github.com/RePsychLing/LMMComplexity.git`
    - `git clone https://github.com/dalejbarr/kronmueller-barr-2007.git`
* [NextJournal article](https://nextjournal.com/dmbates/complexity-in-fitting-linear-mixed-models/)

### Setting up

* Open the `LMMComplexity` directory in VSCode
* Open the file `Complexity.jmd`
* Shift-cmd-P (&#8679;&#8984;P) to open the commands window and search for `Julia: Start REPL`
* Type `]` in the Terminal window in VSCode to get the `pkg` prompt
* pkg> `activate .`
* Use backspace to get back to the julia prompt
* Add/update some packages (get the `pkg` prompt with `]`)
    - pkg> `add Tables@0.2`
    - pkg>`add MixedModels#master`
    - pkg>`add IJulia`

### Convert .jmd to interactive python notebook

* julia> `using Weave`
* julia> `convert_doc("Complexity.jmd", "Complexity.ipynb")`
* julia> `using IJulia`
* julia> `IJulia.notebook(dir=".")`
* Some installation might happen, then your working directory will open in a web browser window. 
* Click on `Complexity.ipynb` to open it
* Put your cursor in a code block and type ctrl-Enter to run the block
    - You will see [*] to the left while it's running, and [1] after it runs.
    - Loading packages can take a long time the first time you run a script because of the precompiling.

Compare models: `MixedModels.likelihoodratiotest(m3, m4)`
