---
title: "Mixed Models in the Julia Programming Language"
---

Convenors: Reinhold Kliegl and Douglas Bates ([Statistical Models for Psychological and Linguistic Data, ZiF Bielefeld](https://www.uni-bielefeld.de/(en)/ZiF/KG/2019StatModels/))

## Schedule

```{r, echo = FALSE, message=FALSE}
require(dplyr, quietly = TRUE)
require(tidyr, quietly = TRUE)
require(kableExtra, quietly = TRUE)

data.frame(day = "Monday",  time = "08:00-09:00", event = "Breakfast") %>%
    add_row(day = "Tuesday",  time = "08:00-09:00", event = "Breakfast") %>%
    add_row(day = "Wednesday",  time = "08:00-09:00", event = "Breakfast") %>%
    add_row(day = "Monday", time = "09:00-10:30", 
            event = "Britta Padberg: Welcome to  [ZiF](https://www.uni-bielefeld.de/(en)/ZiF/)\n\nDouglas Bates: [Introduction to the Julia-based MixedModels package](intro.html)") %>%
    add_row(day = "Tuesday", time = "09:00-10:30", 
            event = "Christina Bergmann: [Reanalysis of ManyBabies1](manybabies.html)\n\nPhillip Alday: [ MixedModels.PCA()](MixedModelsPCA.html)") %>%
    add_row(day = "Wednesday", time = "09:00-10:30", 
            event = "Benedikt Ehinger / Dave Kleinschmidt: [Mixed-model timeseries analysis](https://www.unfoldtoolbox.org/index.html), see [Julia version - very alpha](https://github.com/unfoldtoolbox/unfold.jl)\n\nHannes Matuschek: [Prewhitening of LMMs](https://github.com/RePsychLing/PreWhitening)") %>%
    
    add_row(day = "Monday",  time = "10:30-11:00", event = "Coffee & Tea") %>%
    add_row(day = "Tuesday",  time = "10:30-11:00", event = "Coffee & Tea") %>%
    add_row(day = "Wednesday",  time = "10:30-11:00", event = "Coffee & Tea") %>%
    
    add_row(day = "Monday",  time = "11:00-12:30", event = "[Installation Check](https://github.com/RePsychLing/TutorialSetup)\n\nReinhold Kliegl: [Workflow for a complex LMM example](complex.html)") %>%
    add_row(day = "Tuesday",  time = "11:00-12:30", event = "Dave Kleinschmidt: [StatsModels.jl tour: Contrasts, `@formula`, and Terms](https://repsychling.github.io/contrasts-and-formula/)\n\nBayoan Calderon: Setup of a Julia environment and projects](https://github.com/RePsychLing/Julia-Tips)") %>%
    add_row(day = "Wednesday",  time = "11:00-12:30", event = "Phillip Alday: [MixedModels-lme4 bridge](https://github.com/RePsychLing/MixedModels-lme4-bridge)\n\nDouglas Bates: [Parametric bootstrapping](https://github.com/RePsychLing/Bootstrapping)\n\nPhillip Alday: [Parallel threads](https://github.com/RePsychLing/Parallelism)") %>%
    
    add_row(day = "Monday",  time = "12:30-14:00", event = "Lunch") %>%
    add_row(day = "Tuesday",  time = "12:30-14:00", event = "Lunch") %>%
    add_row(day = "Wednesday",  time = "12:30-14:00", event = "Lunch") %>%
    
    add_row(day = "Monday",  time = "14:00-15:30", event = "Participant Issues") %>%
    add_row(day = "Tuesday",  time = "14:00-15:30", event = "Participant Issues") %>%
    add_row(day = "Wednesday",  time = "14:00-15:30", event = "Participant Issues") %>%
    
    add_row(day = "Monday",  time = "15:30-16:00", event = "Coffee & Tea") %>%
    add_row(day = "Tuesday",  time = "15:30-16:00", event = "Coffee & Tea") %>%
    add_row(day = "Wednesday",  time = "15:30-16:00", event = "Coffee & Tea") %>%
    
    add_row(day = "Monday",  time = "16:00-17:30", event = "Lisa DeBruine: [Power simulation](powersim.html)") %>%
    add_row(day = "Tuesday",  time = "16:00-17:30", event = "Participant Issues") %>%
    add_row(day = "Wednesday",  time = "16:00-17:30", event = "Open forum feedback") %>%
    
    spread(day, event) %>%
    rename(Time = time) %>%
    kable()%>%
    kable_styling(bootstrap_options = c("striped", "hover"))
```


## Notes and Links

* [Tutorial Setup](https://github.com/RePsychLing/TutorialSetup)
* [Github Repositories](https://github.com/RePsychLing)
* [CheatSheet Julia](https://juliadocs.github.io/Julia-Cheat-Sheet/)
* [CheatSheet Julia for r-efugees - see links](https://github.com/JuliaData/DataFrames.jl/issues/1530)
* [Punctuation](https://docs.julialang.org/en/v1/base/punctuation/): brief documentation for mathematical symbols & functions
* Shift-cmd-P in VSCode to get command list
* [Julia Package Management](pkg.html) (by Dave Kleinschmidt)
* To get greek letters, install the latex-input extension in VSCode
    - Click on the Extensions tab in the left column (looks like window panes)
    - Search for `latex-input` and click the install button
    - Now you can type, e.g., `\beta` and tab to get $\beta$
    - Type, e.g., `\_1` (tab) to get subscripts
* In the julia REPL:
    - `]` to access pkg
    - `;` to access the shell
    - `?` to access help
    - `$` to access R (if using RCall)
    - backspace to get back to julia
    - cmd-K to clear the REPL


    
